version: "3.9"

services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    restart: always
    volumes:
      - /var/lib/metabase-data:/metabase-data
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo-db
      - postgres-db
    networks:
      - api-network

  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    volumes:
      - /var/lib/db:/data/db
    env_file: .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - api-network

  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    volumes:
      - /var/lib/pgdata:/var/lib/postgresql/data
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
